# Generated by Django 5.2.13 on 2026-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction Générale'), ('assistant_directeur', 'Assistant Directeur'), ('transit', 'Service Transit'), ('passation', 'Service Passation'), ('logistique', 'Service Logistique'), ('caisse', 'Service Caisse'), ('comptabilite', 'Comptabilité')], default='transit', max_length=50),
        ),
    ]
