# Generated by Django 5.2.13 on 2026-04-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationDouane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_declaration', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nom_navire', models.CharField(blank=True, max_length=150)),
                ('port_arrivee', models.CharField(default='Port de Lomé', max_length=100)),
                ('dtd_montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('autres_frais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_cours', max_length=30)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='dossiers.dossier')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_saisies', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration douanière',
                'db_table': 'declarations_douane',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='EtudeValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit_taxe_douane', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frais_transit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frais_manutention', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frais_portuaires', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('autres_frais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approuve_client', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etude_valeur', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Étude de valeur',
                'db_table': 'etudes_valeur',
            },
        ),
    ]
