# Generated by Django 5.2.13 on 2026-04-19 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_transport', models.CharField(choices=[('maritime', 'Maritime'), ('aerien', 'Aérien'), ('terrestre', 'Terrestre')], max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('transit', 'Transit'), ('passation', 'Passation'), ('logistique', 'Logistique'), ('livraison', 'Livraison'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='nouveau', max_length=30)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='clients.client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'db_table': 'dossiers',
                'ordering': ['-date_debut'],
            },
        ),
    ]
