# Generated by Django 5.2.13 on 2026-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={},
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('transit', 'Transit'), ('logistique_initial', 'Logistique - phase initiale'), ('passation', 'Passation'), ('logistique_final', 'Logistique - phase finale'), ('livraison', 'Livraison'), ('cloture', 'Clôture'), ('archive', 'Archive')], default='nouveau', max_length=30),
        ),
        migrations.AlterModelTable(
            name='dossier',
            table=None,
        ),
    ]
