# Generated by Django 5.2.13 on 2026-06-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_classification_dossier_mode_sortie_contrat_piececontrat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Dossier'},
        ),
        migrations.AlterModelTable(
            name='dossier',
            table='dossiers',
        ),
    ]
