# Generated by Django 5.2.13 on 2026-06-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_alter_dossier_options_alter_dossier_table'),
        ('dossiers', '0004_conteneurdetail_contrat_signature_documentcontrat'),
    ]

    operations = [
    ]
