# Generated by Django 5.2.13 on 2026-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_remove_conteneurdetail_numero_bl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneurdetail',
            name='numero_bl',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° B/L'),
        ),
        migrations.AlterField(
            model_name='historiquedossier',
            name='duree_jours',
            field=models.IntegerField(default=0, help_text='Jours passés dans le statut précédent'),
        ),
    ]
