# Generated by Django 5.2.13 on 2026-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_alter_conteneurdetail_numero_bl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='classification',
            field=models.CharField(choices=[('standard', 'État'), ('urgent', 'Urgent'), ('vip', 'VIP'), ('contentieux', 'Contentieux')], default='standard', max_length=20),
        ),
    ]
