# Generated by Django 5.2.13 on 2026-04-20 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_douane', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('infirme', 'Infirmé')], default='en_attente', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('dossier_conforme', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passation', to='dossiers.dossier')),
                ('traite_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passation',
                'db_table': 'passation',
                'ordering': ['-date_debut'],
            },
        ),
    ]
