# Generated by Django 5.2.13 on 2026-04-21 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_facture', models.CharField(choices=[('emise', 'Émise'), ('recue', 'Reçue')], max_length=20)),
                ('emetteur', models.CharField(blank=True, max_length=200)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='dossiers.dossier')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'db_table': 'factures',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_montant', models.CharField(choices=[('banque', 'Banque'), ('dfu', 'DFU'), ('manutention', 'Manutention'), ('douane', 'Douane'), ('transport', 'Transport'), ('consignataire', 'Consignataire'), ('honoraires', 'Honoraires'), ('frais_portuaires', 'Frais portuaires'), ('frais_transit', 'Frais de transit'), ('remboursement', 'Remboursement'), ('autre', 'Autre')], max_length=40)),
                ('libelle', models.CharField(max_length=200)),
                ('montant_debours', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut_paiement', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='paye', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montants', to='dossiers.dossier')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montants_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Montant',
                'db_table': 'montants',
                'ordering': ['-date_debut'],
            },
        ),
    ]
