# Generated by Django 5.2.13 on 2026-04-27 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('reference_physique', models.CharField(blank=True, max_length=100)),
                ('emplacement_numerique', models.CharField(blank=True, max_length=300)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('archive_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives_creees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Archive',
                'db_table': 'archives',
                'ordering': ['-date_debut'],
            },
        ),
    ]
