# Generated by Django 5.2.13 on 2026-05-04 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_document', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_document', models.CharField(choices=[('bordereau', 'Bordereau'), ('manifeste', 'Manifeste'), ('facture_commerciale', 'Facture commerciale'), ('certificat_origine', "Certificat d'origine"), ('liste_colisage', 'Liste de colisage'), ('bon_livraison', 'Bon de livraison'), ('autre', 'Autre')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=500)),
                ('taille_fichier', models.IntegerField(blank=True, null=True)),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement', 'En traitement'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='en_attente', max_length=30)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('donnees_extraites', models.JSONField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_assignes', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier')),
                ('scanne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_scannes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'documents',
                'ordering': ['-date_scan'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=30)),
                ('nouveau_statut', models.CharField(blank=True, max_length=30)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='documents.document')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Document',
                'db_table': 'historique_documents',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouveau_document', 'Nouveau document'), ('document_assigne', 'Document assigné'), ('action_requise', 'Action requise'), ('document_valide', 'Document validé'), ('document_rejete', 'Document rejeté')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
