# Generated by Django 5.2.13 on 2026-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bordereau', 'Bordereau'), ('manifeste', 'Manifeste'), ('facture_commerciale', 'Facture commerciale'), ('certificat_origine', "Certificat d'origine"), ('liste_colisage', 'Liste de colisage'), ('bon_livraison', 'Bon de livraison'), ('besc', 'BESC (Bordereau Électronique de Suivi des Cargaisons)'), ('connaissement', 'Connaissement / Bill of Lading (OBL)'), ('awb_lta', 'AWB / LTA (Lettre de Transport Aérien)'), ('cmr', 'CMR / Lettre de voiture'), ('declaration_export', "Déclaration d'exportation"), ('autorisation_import', "Autorisation d'importation"), ('assurance_maritime', "Ordre d'assurance maritime"), ('booking', 'Booking (export)'), ('certificat_sanitaire', 'Certificat sanitaire'), ('facture', 'Facture'), ('bae', 'BAE (Bon À Enlever)'), ('bad', 'BAD (Bon À Délivrer)'), ('dfu', 'DFU (Droit de Fret Unique)'), ('autre', 'Autre')], max_length=50),
        ),
    ]
