# Generated by Django 5.2.13 on 2026-04-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('type_camion', models.CharField(choices=[('porteur', 'Porteur'), ('semi_remorque', 'Semi-remorque'), ('remorque', 'Remorque'), ('plateau', 'Plateau'), ('frigorifique', 'Frigorifique'), ('citerne', 'Citerne'), ('autre', 'Autre')], default='porteur', max_length=30)),
                ('capacite_tonnes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nom_chauffeur', models.CharField(blank=True, max_length=150)),
                ('telephone_chauffeur', models.CharField(blank=True, max_length=30)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('en_maintenance', 'En maintenance'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'db_table': 'camions',
                'ordering': ['immatriculation'],
            },
        ),
    ]
