# Generated by Django 5.2.13 on 2026-05-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camion',
            options={'ordering': ['immatriculation'], 'verbose_name': 'Camion'},
        ),
        migrations.RemoveField(
            model_name='camion',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='camion',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='derniere_position_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='derniere_position_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='destination_actuelle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='camion',
            name='dossier_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camions_affectes', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='camion',
            name='marchandise_transportee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='position_actuelle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='camion',
            name='capacite_tonnes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='marque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='camion',
            name='modele',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='camion',
            name='nom_chauffeur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camion',
            name='telephone_chauffeur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='camion',
            name='type_camion',
            field=models.CharField(choices=[('porteur', 'Porteur'), ('semi_remorque', 'Semi-remorque'), ('plateau', 'Plateau'), ('frigorifique', 'Frigorifique'), ('citerne', 'Citerne'), ('autre', 'Autre')], default='porteur', max_length=30),
        ),
        migrations.CreateModel(
            name='PositionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('position_text', models.CharField(blank=True, max_length=200)),
                ('vitesse', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_position', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='camions.camion')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Position Camion',
                'db_table': 'positions_camions',
                'ordering': ['-date_position'],
            },
        ),
    ]
