# Generated by Django 5.2.13 on 2026-04-21 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(blank=True, choices=[('T.TL', 'Port 1 — Terminal T.TL'), ('LCT', 'Port 2 — Terminal LCT'), ('autre', 'Autre terminal')], max_length=20)),
                ('montant_dfu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dfu_paye', models.BooleanField(default=False)),
                ('date_paiement_dfu', models.DateField(blank=True, null=True)),
                ('type_bon', models.CharField(blank=True, choices=[('BAD', 'Bon à Délivrer (BAD)'), ('BAD_manutention', 'BAD Manutention'), ('appointement_LCT', 'Appointement LCT'), ('autre', 'Autre')], max_length=30)),
                ('bon_recupere', models.BooleanField(default=False)),
                ('date_recuperation_bon', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='camions.camion')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistique', to='dossiers.dossier')),
                ('traite_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistiques_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistique',
                'db_table': 'logistique',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_livraison', models.CharField(choices=[('lome', 'Lomé'), ('hors_lome', 'Hors Lomé (Togo)'), ('hors_togo', 'Hors Togo')], max_length=20)),
                ('magasin_destination', models.CharField(blank=True, max_length=200)),
                ('localite', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_livraison_heures', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('echoue', 'Échoué')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('logistique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='logistique.logistique')),
            ],
            options={
                'verbose_name': 'Livraison',
                'db_table': 'livraisons',
                'ordering': ['-date_debut'],
            },
        ),
    ]
